name: DEVOPS
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  CICD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          npm install
          npm run build
      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.DONGTAI_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_SECRET }}
      - name: Push OSS
        run: |
          ossutil cp -rf build/ oss://cloudsec-huoxian-cn/
